ci:
  autofix_commit_msg: "style: apply pre-commit fixes"
  autofix_prs: true
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-check
        files: ^(NuMagSANS|examples|tests|tutorials)/.*\.py$
        args: [--fix]
      - id: ruff-format
        files: ^(NuMagSANS|examples|tests|tutorials)/.*\.py$
