"""Operator-kernel vector fields for local magnetization models.

This library builds vector-valued magnetization fields from scalar kernels and
constant-coefficient differential operators. It is intentionally limited to the
real-space field generation needed by SystemDesigner workflows.
"""

from dataclasses import dataclass
from typing import Optional

import numpy as np


class Kernel:
    """Base interface for scalar kernels."""

    def real(self, positions):
        """Evaluate the scalar kernel in real space."""
        raise NotImplementedError

    def fourier(self, q_vectors):
        """Evaluate the scalar kernel in Fourier space."""
        raise NotImplementedError

    def symbolic_real_expression(self):
        """Return a symbolic real-space expression and coordinate symbols."""
        raise NotImplementedError


class GaussianKernel(Kernel):
    """Three-dimensional Gaussian scalar kernel."""

    def __init__(self, Sigma):
        self.Sigma = np.asarray(Sigma, dtype=float)
        if self.Sigma.shape != (3, 3):
            raise ValueError("Sigma must have shape (3, 3).")

        self.Sigma_inv = np.linalg.inv(self.Sigma)
        self.norm = 1.0 / ((2.0 * np.pi) ** 1.5 * np.sqrt(np.linalg.det(self.Sigma)))

    def real(self, positions):
        positions = np.asarray(positions, dtype=float)
        exponent = np.einsum("...i,ij,...j->...", positions, self.Sigma_inv, positions)
        return self.norm * np.exp(-0.5 * exponent)

    def fourier(self, q_vectors):
        q_vectors = np.asarray(q_vectors, dtype=float)
        exponent = np.einsum("...i,ij,...j->...", q_vectors, self.Sigma, q_vectors)
        return (2.0 * np.pi) ** -1.5 * np.exp(-0.5 * exponent)

    def symbolic_real_expression(self):
        import sympy as sp

        x, y, z = sp.symbols("x y z", real=True)
        coordinates = sp.Matrix([x, y, z])
        sigma_inv = sp.Matrix(self.Sigma_inv)
        quadratic_form = (coordinates.T * sigma_inv * coordinates)[0]
        expression = sp.Float(self.norm) * sp.exp(-sp.Rational(1, 2) * quadratic_form)
        return expression, (x, y, z)


class SechKernel(Kernel):
    """Product hyperbolic-secant scalar kernel."""

    def __init__(self, a):
        self.a = np.asarray(a, dtype=float)
        if self.a.shape != (3,):
            raise ValueError("a must contain three scale parameters.")

    def real(self, positions):
        positions = np.asarray(positions, dtype=float)
        values = np.ones(positions.shape[:-1], dtype=float)
        for axis in range(3):
            values *= (self.a[axis] / np.pi) / np.cosh(self.a[axis] * positions[..., axis])
        return values

    def fourier(self, q_vectors):
        q_vectors = np.asarray(q_vectors, dtype=float)
        values = np.ones(q_vectors.shape[:-1], dtype=float)
        for axis in range(3):
            values *= 1.0 / np.cosh(np.pi * q_vectors[..., axis] / (2.0 * self.a[axis]))
        return values / (2.0 * np.pi) ** 1.5

    def symbolic_real_expression(self):
        import sympy as sp

        x, y, z = sp.symbols("x y z", real=True)
        coordinates = (x, y, z)
        expression = 1
        for coordinate, scale in zip(coordinates, self.a):
            expression *= sp.Float(scale / np.pi) / sp.cosh(sp.Float(scale) * coordinate)
        return expression, coordinates


class DerivedKernel(Kernel):
    """Scalar kernel generated by applying a differential operator."""

    def __init__(
        self,
        real_function,
        symbolic_expression,
        variables,
        label=None,
        base_kernel=None,
        fourier_multiplier=None,
    ):
        self._real_function = real_function
        self.symbolic_expression = symbolic_expression
        self.variables = variables
        self.label = label or "derived kernel"
        self.base_kernel = base_kernel
        self._fourier_multiplier = fourier_multiplier

    def real(self, positions):
        positions = np.asarray(positions, dtype=float)
        values = self._real_function(positions[..., 0], positions[..., 1], positions[..., 2])
        values = np.asarray(values, dtype=float)
        if values.shape == ():
            return np.full(positions.shape[:-1], float(values))
        return values

    def fourier(self, q_vectors):
        if self.base_kernel is None or self._fourier_multiplier is None:
            raise NotImplementedError("This derived kernel has no Fourier representation.")

        q_vectors = np.asarray(q_vectors, dtype=float)
        return self._fourier_multiplier(q_vectors) * self.base_kernel.fourier(q_vectors)

    def symbolic_real_expression(self):
        return self.symbolic_expression, self.variables


class ConstantCoefficientDifferentialOperator:
    """Polynomial differential operator in ``dx``, ``dy``, and ``dz``."""

    def __init__(self, expression, parameters=None):
        try:
            import sympy as sp
            from sympy.parsing.sympy_parser import convert_xor, parse_expr, standard_transformations
        except ImportError as error:
            raise ImportError(
                "Operator-kernel vector fields require sympy. Install NuMagSANS with its Python dependencies."
            ) from error

        self._sp = sp
        self.dx, self.dy, self.dz = sp.symbols("dx dy dz", commutative=True)
        self.qx, self.qy, self.qz = sp.symbols("qx qy qz", real=True)
        transformations = standard_transformations + (convert_xor,)
        self.expression = parse_expr(
            str(expression),
            local_dict={"dx": self.dx, "dy": self.dy, "dz": self.dz},
            transformations=transformations,
        )

        if parameters:
            substitutions = {sp.Symbol(name): value for name, value in parameters.items()}
            self.expression = sp.simplify(self.expression.subs(substitutions))

        self.polynomial = sp.Poly(self.expression, self.dx, self.dy, self.dz)
        if self.polynomial is None:
            raise ValueError("Operator expression must be polynomial in dx, dy, and dz.")

        self.fourier_expression = sp.simplify(
            self.expression.subs(
                {
                    self.dx: sp.I * self.qx,
                    self.dy: sp.I * self.qy,
                    self.dz: sp.I * self.qz,
                }
            )
        )
        self._fourier_function = sp.lambdify(
            (self.qx, self.qy, self.qz),
            self.fourier_expression,
            modules="numpy",
        )

    def symbolic_apply(self, scalar_expression, variables):
        x, y, z = variables
        result = 0
        for powers, coefficient in self.polynomial.terms():
            derivative = scalar_expression
            if powers[0]:
                derivative = self._sp.diff(derivative, x, powers[0])
            if powers[1]:
                derivative = self._sp.diff(derivative, y, powers[1])
            if powers[2]:
                derivative = self._sp.diff(derivative, z, powers[2])
            result += coefficient * derivative
        return self._sp.simplify(result)

    def apply_to_kernel(self, kernel, label=None):
        scalar_expression, variables = kernel.symbolic_real_expression()
        derived_expression = self.symbolic_apply(scalar_expression, variables)
        numeric_function = self._sp.lambdify(variables, derived_expression, modules="numpy")

        def fourier_multiplier(q_vectors):
            q_vectors = np.asarray(q_vectors, dtype=float)
            return self._fourier_function(q_vectors[..., 0], q_vectors[..., 1], q_vectors[..., 2])

        return DerivedKernel(
            real_function=numeric_function,
            symbolic_expression=derived_expression,
            variables=variables,
            label=label or f"{self.expression} applied to kernel",
            base_kernel=kernel,
            fourier_multiplier=fourier_multiplier,
        )


@dataclass
class RealSpaceComponentSpec:
    """Operator expression defining one Cartesian magnetization component."""

    expression: str
    label: Optional[str] = None


class OperatorKernelModel:
    """Vector-valued model assembled from three scalar derived kernels."""

    def __init__(self, kernels, amplitude=1.0, metadata=None):
        if len(kernels) != 3:
            raise ValueError("kernels must contain exactly three scalar kernels.")

        self.kernels = tuple(kernels)
        self.amplitude = float(amplitude)
        self.metadata = metadata or {}

    def real(self, positions):
        positions = np.asarray(positions, dtype=float)
        field = np.stack([kernel.real(positions) for kernel in self.kernels], axis=-1)
        return self.amplitude * field

    def fourier(self, q_vectors):
        q_vectors = np.asarray(q_vectors, dtype=float)
        field = np.stack([kernel.fourier(q_vectors) for kernel in self.kernels], axis=-1)
        return self.amplitude * field


def _as_component_spec(spec):
    if isinstance(spec, RealSpaceComponentSpec):
        return spec
    if isinstance(spec, str):
        return RealSpaceComponentSpec(spec)
    if isinstance(spec, dict):
        return RealSpaceComponentSpec(
            expression=spec["expression"],
            label=spec.get("label"),
        )
    raise TypeError("component_specs entries must be strings, dictionaries, or RealSpaceComponentSpec objects.")


def _as_three_kernels(kernel):
    if isinstance(kernel, (list, tuple)):
        if len(kernel) != 3:
            raise ValueError("When passing multiple kernels, provide exactly three kernels.")
        return tuple(kernel)
    return (kernel, kernel, kernel)


def apply_differential_operator(kernel, expression, parameters=None, label=None):
    """Apply one constant-coefficient differential operator to a scalar kernel."""
    operator = ConstantCoefficientDifferentialOperator(expression, parameters=parameters)
    return operator.apply_to_kernel(kernel, label=label)


def build_operator_kernel_model(
    kernel,
    component_specs=None,
    operator_parameters=None,
    amplitude=1.0,
):
    """Build a vector-valued operator-kernel magnetization model."""
    if component_specs is None:
        component_specs = [
            RealSpaceComponentSpec("-a * dy", label="m_x"),
            RealSpaceComponentSpec("a * dx", label="m_y"),
            RealSpaceComponentSpec("c", label="m_z"),
        ]

    component_specs = [_as_component_spec(spec) for spec in component_specs]
    if len(component_specs) != 3:
        raise ValueError("component_specs must contain exactly three component definitions.")

    if operator_parameters is None:
        operator_parameters = {"a": 1.0, "c": 0.55}

    base_kernels = _as_three_kernels(kernel)
    derived_kernels = []
    for spec, base_kernel in zip(component_specs, base_kernels):
        derived_kernels.append(
            apply_differential_operator(
                base_kernel,
                expression=spec.expression,
                parameters=operator_parameters,
                label=spec.label,
            )
        )

    metadata = {
        "model_family": "operator_kernel",
        "component_specs": [{"expression": spec.expression, "label": spec.label} for spec in component_specs],
        "operator_parameters": dict(operator_parameters),
        "amplitude": amplitude,
    }
    return OperatorKernelModel(derived_kernels, amplitude=amplitude, metadata=metadata)


def _expand_three_values(value, name):
    values = np.asarray(value, dtype=float)
    if values.ndim == 0:
        return np.full(3, float(values))

    values = values.ravel()
    if len(values) != 3:
        raise ValueError(f"{name} must be scalar or contain exactly three values.")
    return values


def _gaussian_sigma_from_params(params):
    if "Sigma" in params:
        Sigma = np.asarray(params["Sigma"], dtype=float)
        if Sigma.shape == (3,):
            return np.diag(Sigma)
        return Sigma

    sigma = _expand_three_values(params.get("sigma", 0.35), "sigma")
    return np.diag(sigma**2)


def _kernel_from_params(params):
    kernel_type = params.get("kernel_type", "gaussian").lower()
    if kernel_type == "gaussian":
        return GaussianKernel(_gaussian_sigma_from_params(params))
    if kernel_type in {"sech", "hyperbolic_sech", "hyperbolic-sech"}:
        return SechKernel(_expand_three_values(params.get("a", 2.0), "a"))
    raise ValueError(f"Unknown operator-kernel kernel_type '{kernel_type}'.")


def _scaled_positions(x, y, z, D, params):
    positions = np.column_stack((x, y, z)).astype(float)
    origin = np.asarray(params.get("origin", (0.0, 0.0, 0.0)), dtype=float)
    if origin.shape != (3,):
        raise ValueError("origin must contain three coordinates.")

    positions = positions - origin
    coordinate_scale = params.get("coordinate_scale", 0.5 * float(D))
    if coordinate_scale is None:
        return positions

    coordinate_scale = float(coordinate_scale)
    if coordinate_scale <= 0.0:
        raise ValueError("coordinate_scale must be positive or None.")

    return positions / coordinate_scale


def unit_field(x, y, z, D, params):
    """Evaluate an operator-kernel vector field on local object coordinates.

    Parameters
    ----------
    x, y, z : array-like
        Local coordinates of the materialized object.
    D : float
        Characteristic object diameter. By default coordinates are scaled by
        ``D/2`` before evaluating the kernel model.
    params : dict
        Operator-kernel model parameters. Common keys are ``kernel_type``,
        ``sigma`` or ``Sigma``, ``component_specs``, ``operator_parameters``,
        ``coordinate_scale``, ``amplitude``, and ``normalize``.
        ``component_specs`` contains three polynomial differential operators
        in ``dx``, ``dy``, and ``dz``. Each operator is applied to the selected
        scalar kernel to generate one raw Cartesian component. Set
        ``normalize=False`` to keep those raw component amplitudes instead of
        normalizing the final vector field. Normalization defaults to True.
    """
    params = dict(params)
    positions = _scaled_positions(x, y, z, D, params)
    kernel = _kernel_from_params(params)
    model = build_operator_kernel_model(
        kernel=kernel,
        component_specs=params.get("component_specs"),
        operator_parameters=params.get("operator_parameters"),
        amplitude=params.get("amplitude", 1.0),
    )
    field = model.real(positions)

    if params.get("normalize", True):
        norm = np.linalg.norm(field, axis=1)
        mask = norm > 0.0
        field[mask] /= norm[mask, None]

    return field[:, 0], field[:, 1], field[:, 2]
