"""Generate NuMagSANS example 1 input data with the SystemDesigner workflow.

This generator expresses the example as a replicated single-object system:

    one local spherical object
    -> several equivalent local magnetic field variants m_1, m_2, ...
    -> five object centers in StructData.csv
    -> optional RotData loop data generated by the workflow

The magnetic field is a linear vortex with ``kappa = 0``. In the current
VectorFieldModels/SphericalVectorFieldLib this reduces to a homogeneous local
+z magnetization, which matches the simple magnetic state used by the original
example.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import numpy as np

from NuMagSANS.SystemDesigner.Workflows import write_spherical_replication_vectorfield_sweep

BASE_DIR = Path(__file__).resolve().parent
REAL_SPACE_DIR = BASE_DIR / "RealSpaceData"

DEFAULT_OBJECT_CENTERS = np.array(
    [
        (0.0, 0.0, 0.0),
        (10.0, 0.0, 0.0),
        (0.0, 10.0, 0.0),
        (0.0, 0.0, 10.0),
        (20.0, 0.0, 0.0),
    ],
    dtype=float,
)


def linear_vortex_kappa_zero_cases(n_datasets: int) -> list[dict]:
    """Return equivalent homogeneous +z field cases as linear vortices."""
    n_datasets = int(n_datasets)
    if n_datasets <= 0:
        raise ValueError("n_datasets must be a positive integer.")

    return [
        {
            "field_type": "vortex",
            "profile_type": "linear",
            "xi_type": "cylindrical_xi",
            "kappa": 0.0,
            "turns": 1.0,
        }
        for _ in range(n_datasets)
    ]


def write_struct_data(real_space_dir: Path, object_centers: np.ndarray = DEFAULT_OBJECT_CENTERS) -> Path:
    """Write global object-center positions to ``StructData.csv``."""
    real_space_dir = Path(real_space_dir)
    real_space_dir.mkdir(parents=True, exist_ok=True)

    structdata_path = real_space_dir / "StructData.csv"
    np.savetxt(structdata_path, np.asarray(object_centers, dtype=float), fmt="%.10g", delimiter=" ")
    return structdata_path


def generate_real_space_data_system_designer(
    output_dir: Path = BASE_DIR,
    radius: float = 5.0,
    spacing: float = 0.3554,
    atomtype: str = "Fe",
    n_datasets: int = 3,
    clean: bool = True,
) -> dict:
    """Generate example 1 data through the SystemDesigner workflow."""
    output_dir = Path(output_dir)
    real_space_dir = output_dir / "RealSpaceData"

    if clean and real_space_dir.exists():
        shutil.rmtree(real_space_dir)

    summary = write_spherical_replication_vectorfield_sweep(
        output_dir=output_dir,
        R=radius,
        a=spacing,
        atomtype=atomtype,
        n_replications=len(DEFAULT_OBJECT_CENTERS),
        field_parameter_cases=linear_vortex_kappa_zero_cases(n_datasets),
        n_rotdata=1,
        beta_min=0.0,
        beta_max=0.0,
        rotation_seed=1,
    )

    structdata_path = write_struct_data(real_space_dir)
    summary["structdata_path"] = str(structdata_path)
    summary["config_hints"].update(
        {
            "StructData_activate": 1,
            "StructDataFilename": str(structdata_path),
            "User_Selection": list(range(1, n_datasets + 1)),
        }
    )

    return summary


def parse_args() -> argparse.Namespace:
    """Parse command line arguments for manual data generation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=BASE_DIR)
    parser.add_argument("--radius", type=float, default=5.0)
    parser.add_argument("--spacing", type=float, default=0.3554)
    parser.add_argument("--atomtype", type=str, default="Fe")
    parser.add_argument("--n-datasets", type=int, default=3)
    parser.add_argument("--no-clean", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Generate the example data set from command line parameters."""
    args = parse_args()
    summary = generate_real_space_data_system_designer(
        output_dir=args.output_dir,
        radius=args.radius,
        spacing=args.spacing,
        atomtype=args.atomtype,
        n_datasets=args.n_datasets,
        clean=not args.no_clean,
    )

    print(f"Generated RealSpaceData in: {summary['real_space_dir']}")
    print("NuMagSANS config hints:")
    for key, value in summary["config_hints"].items():
        print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
