name: Sphinx

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y doxygen
          pip install sphinx furo breathe myst-parser
      - name: Build docs
        working-directory: docs
        run: |
          doxygen Doxyfile || echo "No Doxyfile found"
          sphinx-build -b html . _build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
